### ISSUE TITLE
GTK4 bindings

### ISSUE THREAD

**Issue by pdf** [diamondburned/gotk4-layer-shell#1]
Hi, looks like currently only GTK3 bindings are available?

Would it be possible to add the GTK4 bindings, per https://github.com/wmww/gtk4-layer-shell ?

**Comment by diamondburned** [comment]
GTK4 bindings have been added in 27e830df630b27715fee6ef561f0a2b8178464b3.

**Comment by abenz1267** [comment]
I'm confused as how i'd use this with gotk4. `gtklayershell.InitForWindow(window)` expects a GTK3 window.

What am i missing?
