### ISSUE TITLE
Getting error when trying to change anchors in a running application

### ISSUE THREAD

**Issue by abenz1267** [diamondburned/gotk4-layer-shell#2]
Hi,

I'm getting this error when trying to change anchors in a program where anchors have been set before:

```
INFO Error 71 (Protocol error) dispatching to Wayland display. priority=5 code_file=../gtk/gdk/wayland/gdkeventsource.c code_line=220 code_func=_gdk_wayland_display_queue_events glib_domain=Gdk
```

or 

```
INFO Error reading events from display: Connection reset by peer priority=5 code_file=../gtk/gdk/wayland/gdkeventsource.c code_line=116 code_func=gdk_event_source_check glib_domain=Gdk
```

I'm not sure if this is related to this library or gtk4-layer-shell directly. This happens on both sway and hyprland... so i assume it's not the WM.

It's crashing when setting an anchor from "true" to "false". Take that observation with a grain of salt though.

Regards

**Comment by diamondburned** [comment]
Do you have reproducing code? Can you reproduce this in C?

**Comment by diamondburned** [comment]
`WAYLAND_DEBUG=1` can also help with this.

**Comment by abenz1267** [comment]
Thanks for your time. I've actually created a minimal app to test this... and it works. so it must be something in my actual code. I'll investigate.
